require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ChatApp' do
  use_frameworks!

  # Pods for ChatApp
  pod 'MessageKit'

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  pod 'Alamofire'
  pod 'Kingfisher'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


end
